---

- name: Use specific version {{ packer_product }}
  ansible.builtin.set_fact:
    packer_product_version: "{{ vars[packer_product + '_version'] }}"
  when: vars[packer_product + '_version'] is defined

- name: Get version
  when: vars[packer_product + '_version'] is not defined
  block:

    - name: Get latest release of a public repository
      ansible.builtin.uri:
        url: https://api.github.com/repos/hashicorp/{{ packer_product }}/releases/latest
      check_mode: no
      register: packer_product_release_latest
      when: packer_product in [ 'vault' ]

    - name: Register the version only
      ansible.builtin.set_fact:
        packer_product_version: "{{ packer_product_release_latest['json']['name'] | regex_replace('^v') }}"
      when: packer_product in [ 'vault' ]

    - name: Get latest release of a public repository
      ansible.builtin.uri:
        url: https://checkpoint-api.hashicorp.com/v1/check/{{ packer_product }}
      check_mode: no
      register: packer_product_release_latest
      when: packer_product not in [ 'vault' ]

    - name: Register the version only
      ansible.builtin.set_fact:
        packer_product_version: "{{ packer_product_release_latest['json']['current_version'] | regex_replace('^v') }}"
      when: packer_product not in [ 'vault' ]

- name: Install packages required to unpack
  ansible.builtin.package:
    name: unzip
    state: present

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  changed_when: false
  register: __tmpdir

- name: Download and unpack binary
  ansible.builtin.unarchive:
    src: "{{ packer_product_url }}"
    dest: "{{ __tmpdir.path }}"
    remote_src: yes
  changed_when: false

- name: Copy binary to final location
  ansible.builtin.copy:
    src: "{{ __tmpdir.path }}/{{ packer_product }}"
    dest: /usr/local/bin/{{ packer_product }}
    mode: "0755"
    remote_src: yes
  become: true

- name: Delete temporary directory
  ansible.builtin.file:
    path: "{{ __tmpdir.path }}"
    state: absent
  changed_when: false
