---

- name: RedHat family
  when: ansible_os_family == 'RedHat'
  become: true
  block:

    - name: Import the hashicorp GPG key (RPM)
      ansible.builtin.rpm_key:
        key: https://rpm.releases.hashicorp.com/gpg
        state: present

    - name: Get YUM repository definition (Fedora)
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0644'
      when: ansible_distribution == 'Fedora'

    - name: Get YUM repository definition (!Fedora)
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0644'
      when: ansible_distribution != 'Fedora'


- name: Debian family
  when: ansible_os_family == 'Debian'
  become: true
  block:

    - name: Download APT signing key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp.asc
        mode: "0644"

    - name: Convert APT key into binary format
      ansible.builtin.command:
        cmd: gpg --batch --yes --no-tty --dearmor -o /tmp/hashicorp.gpg /tmp/hashicorp.asc
      changed_when: false

    - name: Import Microsoft GPG key
      ansible.builtin.apt_key:
        state: present
        file: /tmp/hashicorp.gpg
        keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg
      when: ansible_distribution_major_version | int < 12

    - name: Copy APT signing key into the proper drop-in directory
      ansible.builtin.copy:
        src: /tmp/hashicorp.gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp.gpg
        remote_src: yes
        mode: "0644"
      when: ansible_distribution_major_version | int >= 12

    - name: Setup Microsoft APT repository  # noqa jinja[spacing]
      ansible.builtin.apt_repository:
        filename: hasicorp
        repo: >-
          {%- if ansible_distribution_major_version | int < 12 -%}
          deb [arch=amd64,arm64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
          {%- else -%}
          deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
          {%- endif -%}
        state: present

- name: Install the package
  ansible.builtin.package:
    name: "{{ packer_product }}"
    state: present
  become: true
